#!/usr/bin/env bash

read -p "Class (SE, CS, Inf): " class
read -p "Lab # (e.g. 1): " lab_id

if [ ! -f ./src/${class}/Lab${lab_id}.hs ]; then
    echo Lab report does not exist, use ./mkreport to create it
    exit
fi

xelatex_bin=~/.texlive/bin/x86_64-linux/xelatex

report_id=${class}-Lab${lab_id}
report_tex_file=${report_id}.tex

touch ./renders/${report_tex_file}

gnome-terminal \
  --tab --working-directory="`pwd`" -e "vim src/${class}/Lab${lab_id}.hs" \
  --tab --working-directory="`pwd`" --title="${report_id} GHCi" -e "stack ghci" \
  --tab --working-directory="`pwd`/renders" --title="${report_id} TeX Runner" \
    -e "bash -c \"while inotifywait -e close_write ${report_tex_file}; do ${xelatex_bin} ${report_tex_file}; done\""
