#!/usr/bin/env bash

read -p "Class (SE, CS, Inf): " class
read -p "Lab # (e.g. 1): " lab_id

echo "Creating a report for ${class} Lab${lab_id}"

read -p "Is this correct (y/n)? " proceeding
[ "${proceeding}" != "y" ] && [ "${proceeding}" != "Y" ] && exit 0

mkdir -p "src/${class}"

cat <<EOF > "src/${class}/Lab${lab_id}.hs"
module ${class}.Lab${lab_id} where

import ReportBase

writeReport :: IO ()
writeReport = renderFile "./renders/${class}-Lab${lab_id}.tex" (execLaTeXM reportTeX)

reportTeX :: LaTeXM ()
reportTeX = do
  baseHeader
  document $ do
    -- TODO: change the subject
    baseTitlePage ("ЛАБОРАТОРНАЯ РАБОТА №${lab_id}", "Предмет", "2017 г.")
    -- ...
EOF
