#!/usr/bin/env bash

read -p "Class (SE, CS, Inf): " class
read -p "Report name (e.g. Lab1): " report

echo "Creating a report for ${class} ${report}"

read -p "Is this correct (y/n)? " proceeding
[ "${proceeding}" != "y" ] && [ "${proceeding}" != "Y" ] && exit 0

mkdir -p "src/${class}"

cat <<EOF > "src/${class}/${report}.hs"
module ${class}.${report} where

import ReportBase

writeReport :: IO ()
writeReport = renderFile "./renders/${class}-${report}.tex" (execLaTeXM reportTeX)

reportTeX :: LaTeXM ()
reportTeX = do
  baseHeader
  document $ do
    -- TODO: change the subject
    baseTitlePage ("Работа", "Предмет", "2017 г.")
    -- ...
EOF
